language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
 - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install --no-interaction --optimize-autoloader

script:
 - vendor/bin/phpspec run --verbose --no-interaction
