language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
 - composer install --dev -o -n

script:
 - vendor/bin/phpunit --testdox --coverage-clover=coverage.xml

after_success:
 - bash <(curl -s https://codecov.io/bash)
